services:
  ubuntu-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu-bash
    tty: true
    stdin_open: true
    volumes:
      - ./:/app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mylittlepassword
    volumes:
      - mongo_data:/data/db
      
volumes:
  mongo_data: